### ISSUE TITLE
bundle-wizard is great – thank you

### ISSUE THREAD

**Issue by iamakulov** [aholachek/bundle-wizard#11]
Hey, just wanted to drop by and say thanks for creating `bundle-wizard`.

I’ve just recently learned about `bundle-wizard` and have used it a couple times, and it’s _so_ great and convenient for analyzing sites. The attention to detail is incredible: I love how different modules are highlighted differently (makes it much easier to parse bundle contents than when looking at all-white `source-map-explorer`); and how clicking a concrete module shows its content (with syntax highlighting!). The captured “long task” warnings are also 💯.

So, thanks a lot for making this! `bundle-wizard` is just great.

**Comment by aholachek** [comment]
I'm very happy this has been helpful for you!! I made it because I love `source-map-explorer` but I'm lazy and I wasn't using it as much as I should have, so I wanted it to be easier.
I work on `bundle-wizard` on-and-off so I can't promise a quick response, but please do let me know if you ever have any suggestions or run into issues.
